
CREATE TABLE IF NOT EXISTS streams (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	track_id VARCHAR NOT NULL,
	track_name VARCHAR,
	duration_ms INT8,
	played_at TIMESTAMPTZ NOT NULL,
	context VARCHAR,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE streams
ADD CONSTRAINT streams_track_fkey FOREIGN KEY (track_id) REFERENCES tracks (id)