CREATE TABLE builder.genres (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	raw_genre VARCHAR,
	main_genre VARCHAR,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)